version: 2
jobs:
  "test-infra/deploy/prow":
    docker:
      - image: amazon/aws-cli:2.6.3
    steps:
      - checkout
      - run:
          name: Deploy prow
          command: |
            yum update -y
            yum install jq unzip git wget curl which make golang -y
            wget "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" -O /usr/local/bin/kubectl
            chmod +x /usr/local/bin/kubectl
            ./tools/deploy_prow.sh
workflows:
  version: 2
  build:
    jobs:
      - "test-infra/deploy/prow":
          requires:
            - test-infra/deploy/terraform
          context: test-infra
          filters:
            branches:
              only: master
